### ISSUE TITLE
raise TypeError("str expected, not %s" % type(value).__name__) on pip3 install pyjq on macos bigsur (

### ISSUE THREAD

**Issue by nyetwurk** [doloopwhile/pyjq#54]
```
Collecting pyjq
  Using cached pyjq-2.5.1.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pyjq
  Building wheel for pyjq (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/tmp6k1b22ch
       cwd: /private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-install-men_wns5/pyjq_4e5695cc551842b0b3278bc2f1bb3830
```

```
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 97, in <module>
      setup(
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/pip-build-env-8_3ypyh0/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 31, in run
      self._build_oniguruma()
    File "setup.py", line 43, in _build_oniguruma
      self._build_lib(
    File "setup.py", line 71, in _build_lib
      os.environ['MACOSX_DEPLOYMENT_TARGET'] = macosx_deployment_target
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
      value = self.encodevalue(value)
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
      raise TypeError("str expected, not %s" % type(value).__name__)
  TypeError: str expected, not int
  ----------------------------------------
  ERROR: Failed building wheel for pyjq
Failed to build pyjq
ERROR: Could not build wheels for pyjq which use PEP 517 and cannot be installed directly
```

**Comment by nyetwurk** [comment]
```
os.environ['MACOSX_DEPLOYMENT_TARGET'] = macosx_deployment_target
```
should probably be
```
os.environ['MACOSX_DEPLOYMENT_TARGET'] = str(macosx_deployment_target)
```

**Comment by lonnylot** [comment]
I'm also running into an issue on Big Sur. Slightly different traceback, but same `TypeError: str expected, not int`

```bash
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/08/s0g16n5d6wd3d1_xch8jgg740000gn/T/pip-install-ll2pelcj/pyjq_a1467708bb55401abe6c0c537398587a/setup.py", line 93, in <module>
        setup(
      File "/Users/lonnykapelushnik/Development/cloudmapper/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/lonnykapelushnik/Development/cloudmapper/venv/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/08/s0g16n5d6wd3d1_xch8jgg740000gn/T/pip-install-ll2pelcj/pyjq_a1467708bb55401abe6c0c537398587a/setup.py", line 30, in run
        self._build_oniguruma()
      File "/private/var/folders/08/s0g16n5d6wd3d1_xch8jgg740000gn/T/pip-install-ll2pelcj/pyjq_a1467708bb55401abe6c0c537398587a/setup.py", line 39, in _build_oniguruma
        self._build_lib(
      File "/private/var/folders/08/s0g16n5d6wd3d1_xch8jgg740000gn/T/pip-install-ll2pelcj/pyjq_a1467708bb55401abe6c0c537398587a/setup.py", line 67, in _build_lib
        os.environ['MACOSX_DEPLOYMENT_TARGET'] = macosx_deployment_target
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
        value = self.encodevalue(value)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not int
```

**Comment by lonnylot** [comment]
I dug into this a tad more and it seems to be a Python issue:

https://bugs.python.org/issue42504

**Comment by NaturalBornCamper** [comment]
Anyone found any workaround for this issue? I'm also getting the
```
  ERROR: Failed building wheel for pyjq
ERROR: Could not build wheels for pyjq which use PEP 517 and cannot be installed directly
```
Errors.

I got the same on Windows with:
-Basic Python installation folder
-venv
-pipenv

Using Python versions:
-3.6
-3.7
-3.8

With Pip versions:
-18.0
-18.1
-19.x
-21.x

So it doesn't look like it's a Python version, environment or pip version issue.

**Comment by w0rmr1d3r** [comment]
The Python issue in in "resolved" stage !
