### ISSUE TITLE
Unable to install pyjq on MacOs big sur or Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by serialp** [doloopwhile/pyjq#58]
Hello, whatever the solution I came up with to setup cloudmapper, it fails at the pyjq install...

```
pip3 install --user pipenv
cd cloudmapper/; pipenv install --skip-lock
```

is it related to the below issue ? 

https://github.com/doloopwhile/pyjq/issues/54
https://bugs.python.org/issue42504

Please find hereunder my logs:

> Installing dependencies from Pipfile...
> An error occurred while installing pyjq==2.3.1! Will try again.
> An error occurred while installing seaborn==0.10.1! Will try again.
>   🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 37/37 — 00:00:44
> Installing initially failed dependencies...
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
> [InstallError]:       retcode = do_install(
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 2052, in do_install
> [InstallError]:       do_init(
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 1304, in do_init
> [InstallError]:       do_install_dependencies(
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 899, in do_install_dependencies
> [InstallError]:       batch_install(
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 796, in batch_install
> [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
> [InstallError]:   File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 703, in _cleanup_procs
> [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
> [pipenv.exceptions.InstallError]: Collecting pyjq==2.3.1
> [pipenv.exceptions.InstallError]:   Using cached pyjq-2.3.1.tar.gz (2.1 MB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied: six in /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/lib/python3.8/site-packages (from pyjq==2.3.1->-r /var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pipenv-8bez_ooa-requirements/pipenv-r8czubvu-requirement.txt (line 1)) (1.14.0)
> [pipenv.exceptions.InstallError]: Building wheels for collected packages: pyjq
> [pipenv.exceptions.InstallError]:   Building wheel for pyjq (setup.py): started
> [pipenv.exceptions.InstallError]:   Building wheel for pyjq (setup.py): finished with status 'error'
> [pipenv.exceptions.InstallError]:   ERROR: Command errored out with exit status 1:
> [pipenv.exceptions.InstallError]:    command: /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"'; __file__='"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-wheel-dbvkaevy
> [pipenv.exceptions.InstallError]:        cwd: /private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/
> [pipenv.exceptions.InstallError]:   Complete output (44 lines):
> [pipenv.exceptions.InstallError]:   running bdist_wheel
> [pipenv.exceptions.InstallError]:   running build
> [pipenv.exceptions.InstallError]:   running build_py
> [pipenv.exceptions.InstallError]:   creating build
> [pipenv.exceptions.InstallError]:   creating build/lib.macosx-11-x86_64-3.8
> [pipenv.exceptions.InstallError]:   copying pyjq.py -> build/lib.macosx-11-x86_64-3.8
> [pipenv.exceptions.InstallError]:   warning: build_py: byte-compiling is disabled, skipping.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:   running build_ext
> [pipenv.exceptions.InstallError]:   Traceback (most recent call last):
> [pipenv.exceptions.InstallError]:     File "<string>", line 1, in <module>
> [pipenv.exceptions.InstallError]:     File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 93, in <module>
> [pipenv.exceptions.InstallError]:       setup(
> [pipenv.exceptions.InstallError]:     File "/Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
> [pipenv.exceptions.InstallError]:       return distutils.core.setup(**attrs)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
> [pipenv.exceptions.InstallError]:       dist.run_commands()
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
> [pipenv.exceptions.InstallError]:       self.run_command(cmd)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:       cmd_obj.run()
> [pipenv.exceptions.InstallError]:     File "/Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
> [pipenv.exceptions.InstallError]:       self.run_command('build')
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
> [pipenv.exceptions.InstallError]:       self.distribution.run_command(command)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:       cmd_obj.run()
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
> [pipenv.exceptions.InstallError]:       self.run_command(cmd_name)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
> [pipenv.exceptions.InstallError]:       self.distribution.run_command(command)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:       cmd_obj.run()
> [pipenv.exceptions.InstallError]:     File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 30, in run
> [pipenv.exceptions.InstallError]:       self._build_oniguruma()
> [pipenv.exceptions.InstallError]:     File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 39, in _build_oniguruma
> [pipenv.exceptions.InstallError]:       self._build_lib(
> [pipenv.exceptions.InstallError]:     File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 67, in _build_lib
> [pipenv.exceptions.InstallError]:       os.environ['MACOSX_DEPLOYMENT_TARGET'] = macosx_deployment_target
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 680, in __setitem__
> [pipenv.exceptions.InstallError]:       value = self.encodevalue(value)
> [pipenv.exceptions.InstallError]:     File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 750, in encode
> [pipenv.exceptions.InstallError]:       raise TypeError("str expected, not %s" % type(value).__name__)
> [pipenv.exceptions.InstallError]:   TypeError: str expected, not int
> [pipenv.exceptions.InstallError]:   ----------------------------------------
> [pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for pyjq
> [pipenv.exceptions.InstallError]:   Running setup.py clean for pyjq
> [pipenv.exceptions.InstallError]: Failed to build pyjq
> [pipenv.exceptions.InstallError]: Installing collected packages: pyjq
> [pipenv.exceptions.InstallError]:     Running setup.py install for pyjq: started
> [pipenv.exceptions.InstallError]:     Running setup.py install for pyjq: finished with status 'error'
> [pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
> [pipenv.exceptions.InstallError]:      command: /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"'; __file__='"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-record-1eezjp50/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/include/site/python3.8/pyjq
> [pipenv.exceptions.InstallError]:          cwd: /private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/
> [pipenv.exceptions.InstallError]:     Complete output (46 lines):
> [pipenv.exceptions.InstallError]:     running install
> [pipenv.exceptions.InstallError]:     running build
> [pipenv.exceptions.InstallError]:     running build_py
> [pipenv.exceptions.InstallError]:     creating build
> [pipenv.exceptions.InstallError]:     creating build/lib.macosx-11-x86_64-3.8
> [pipenv.exceptions.InstallError]:     copying pyjq.py -> build/lib.macosx-11-x86_64-3.8
> [pipenv.exceptions.InstallError]:     warning: build_py: byte-compiling is disabled, skipping.
> [pipenv.exceptions.InstallError]:
> [pipenv.exceptions.InstallError]:     running build_ext
> [pipenv.exceptions.InstallError]:     Traceback (most recent call last):
> [pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>
> [pipenv.exceptions.InstallError]:       File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 93, in <module>
> [pipenv.exceptions.InstallError]:         setup(
> [pipenv.exceptions.InstallError]:       File "/Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
> [pipenv.exceptions.InstallError]:         return distutils.core.setup(**attrs)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
> [pipenv.exceptions.InstallError]:         dist.run_commands()
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
> [pipenv.exceptions.InstallError]:         self.run_command(cmd)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:         cmd_obj.run()
> [pipenv.exceptions.InstallError]:       File "/Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
> [pipenv.exceptions.InstallError]:         return orig.install.run(self)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
> [pipenv.exceptions.InstallError]:         self.run_command('build')
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
> [pipenv.exceptions.InstallError]:         self.distribution.run_command(command)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:         cmd_obj.run()
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
> [pipenv.exceptions.InstallError]:         self.run_command(cmd_name)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
> [pipenv.exceptions.InstallError]:         self.distribution.run_command(command)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
> [pipenv.exceptions.InstallError]:         cmd_obj.run()
> [pipenv.exceptions.InstallError]:       File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 30, in run
> [pipenv.exceptions.InstallError]:         self._build_oniguruma()
> [pipenv.exceptions.InstallError]:       File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 39, in _build_oniguruma
> [pipenv.exceptions.InstallError]:         self._build_lib(
> [pipenv.exceptions.InstallError]:       File "/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py", line 67, in _build_lib
> [pipenv.exceptions.InstallError]:         os.environ['MACOSX_DEPLOYMENT_TARGET'] = macosx_deployment_target
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 680, in __setitem__
> [pipenv.exceptions.InstallError]:         value = self.encodevalue(value)
> [pipenv.exceptions.InstallError]:       File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 750, in encode
> [pipenv.exceptions.InstallError]:         raise TypeError("str expected, not %s" % type(value).__name__)
> [pipenv.exceptions.InstallError]:     TypeError: str expected, not int
> [pipenv.exceptions.InstallError]:     ----------------------------------------
> [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"'; __file__='"'"'/private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-install-7m4e96ks/pyjq_abce72f03b2c422d9a98ef71102e0034/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/26/pmmcdlhx727ffbxy2ld7m86h0000gn/T/pip-record-1eezjp50/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hiyaa/.local/share/virtualenvs/cloudmapper-WzNltrOW/include/site/python3.8/pyjq Check the logs for full command output.
> ERROR: Couldn't install package: pyjq
>  Package installation failed...
>   ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/2 —

Many thanks !

**Comment by nraw** [comment]
`brew install automake`
this solved the issue for me. Got the idea from here: https://github.com/buffer/pylibemu/issues/24

**Comment by aslangencer** [comment]
`brew install autoconf libtool` fixed it for me.

**Comment by narasimha10998** [comment]
This one worked for me as well: `brew install autoconf libtool`
