### ISSUE TITLE
ERROR: Could not build wheels for pyjq,  unable to install pyjq in mac os

### ISSUE THREAD

**Issue by sudalking94** [doloopwhile/pyjq#70]
Traceback (most recent call last):
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 97, in <module>
      setup(
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/vj/chqg3bd53m53ljhxcftmrqym0000gn/T/pip-build-env-1zulvgpg/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 32, in run
      self._build_libjq()
    File "setup.py", line 57, in _build_libjq
      self._build_lib(
    File "setup.py", line 74, in _build_lib
      subprocess.check_call(command, cwd=lib_dir)
    File "/Users/junwo/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for pyjq
Failed to build pyjq
ERROR: Could not build wheels for pyjq, which is required to install pyproject.toml-based projects

this is my a part of error log.
i have installed flex, bison (3.0 or newer), libtool, make, automake and autoconf .
but i could not install pyjq

**Comment by egonbraun** [comment]
Yeah, same thing for me on intel macOS running Monterey and Ubuntu 21.04 and Python 3.9.9 and Python 3.8.12.

**Comment by gangofnuns** [comment]
I was able to manage using Python 3.9.9 and updated dependencies.   Hope that helps. 

  Downloading pyjq-2.5.2-cp39-cp39-macosx_11_0_x86_64.whl (33 kB)
Installing collected packages: pyjq
Successfully installed pyjq-2.5.2

Looks like yours may be failing on the autoconf dependency.  
I'm using the latest build from homebrew for that:  

autoconf --version
autoconf (GNU Autoconf) 2.71

Hope that helps.   Best of luck!

**Comment by peter-gy** [comment]
I also had trouble building the wheel, the subprocess ran into problems with this message:

```text
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
```

I managed to solve the issue by installing `automake`:

```shell
brew install automake
```

In general, after installing Xcode, the following dependencies should suffice to build the wheel:

```shell
brew install autoconf automake libtool
```
